# Generated by Django 5.2.5 on 2025-08-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('student', 'Student'), ('candidate', 'Candidate')], default='student', max_length=20),
        ),
    ]
